[package]
name = "ray-tracing-gallery"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
ash = "0.33.2"
ash-window = "0.7.0"
byte-strings = "0.1.3"
env_logger = "0.9.0"
gpu-allocator = "0.9.0"
winit = "0.25.0"
