[package]
name = "shared-structs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.19.0", default-features = false, features = ["libm"] }
